"""initial schema

Revision ID: 02f207f86d70
Revises:
Create Date: 2026-09-14 22:55:48.599981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f207f86d70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('home_airport', sa.String(), nullable=False),
    sa.Column('loyalty_tier', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('traveler_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('trip_value', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPERATIONAL', 'DISRUPTED', 'RECOVERING', 'RECOVERED', name='tripstatus'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MONITORING', 'RISK', 'RECOVERY', 'BOOKING', 'SYSTEM', 'DISRUPTION', name='activitytype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('FLIGHT', 'CONNECTION', 'TRANSFER', 'HOTEL', 'ACTIVITY', 'RETURN', name='nodecategory'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('flexible', sa.Boolean(), nullable=False),
    sa.Column('fixed_end', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('confirmation', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('cancellation_policy', sa.String(), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('refund_percentage', sa.Float(), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('dependency_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'AT_RISK', 'BROKEN', 'DELAYED', 'CANCELLED', 'RECOVERED', name='nodestatus'), nullable=False),
    sa.Column('status_reason', sa.String(), nullable=True),
    sa.Column('caused_by', sa.String(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('origin_code', sa.String(), nullable=True),
    sa.Column('destination_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'SYSTEM', name='notificationseverity'), nullable=False),
    sa.Column('category', sa.Enum('RISK', 'RECOVERY', 'BOOKING', 'SYSTEM', name='notificationcategory'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('FLIGHT', 'CONNECTION', 'TRANSFER', 'HOTEL', 'ACTIVITY', 'RETURN', name='nodecategory'), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('confirmation', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('cancellation_policy', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'AT_RISK', 'BROKEN', 'DELAYED', 'CANCELLED', 'RECOVERED', name='nodestatus'), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['itinerary_nodes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.Enum('HARD', 'SOFT', name='dependencytype'), nullable=False),
    sa.Column('min_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('risk_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('upstream_reference', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'AT_RISK', 'BROKEN', 'RECOVERED', name='edgestatus'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('animated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['itinerary_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['itinerary_nodes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disruptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FLIGHT_DELAY', 'FLIGHT_CANCELLATION', 'MISSED_CONNECTION', 'HOTEL_CHECKIN_CONFLICT', 'HOTEL_CANCELLATION', 'TRANSFER_FAILURE', 'ACTIVITY_CANCELLATION', 'ACTIVITY_DELAY', 'AIRPORT_CLOSURE', name='disruptiontype'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('primary_node_id', sa.String(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('impact_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='impactlevel'), nullable=False),
    sa.Column('direct_impact', sa.Integer(), nullable=False),
    sa.Column('downstream_impact', sa.Integer(), nullable=False),
    sa.Column('financial_exposure', sa.Float(), nullable=False),
    sa.Column('refund_exposure', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['primary_node_id'], ['itinerary_nodes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('snapshot_type', sa.Enum('NODE', 'TRIP', name='snapshottype'), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('risk_percent', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['itinerary_nodes.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cascade_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('disruption_id', sa.String(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['itinerary_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('disruption_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('tag_color', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost_delta', sa.Float(), nullable=False),
    sa.Column('time_impact_minutes', sa.Integer(), nullable=False),
    sa.Column('bookings_preserved', sa.Integer(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('refund_recovered', sa.Float(), nullable=False),
    sa.Column('residual_risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recovery_plan_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.Enum('REBOOKED', 'RESCHEDULED', 'CANCELLED', 'PRESERVED', 'NEW', name='changetype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('new_scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('new_scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('new_cost', sa.Float(), nullable=True),
    sa.Column('new_provider', sa.String(), nullable=True),
    sa.Column('new_confirmation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['itinerary_nodes.id'], ),
    sa.ForeignKeyConstraint(['recovery_plan_id'], ['recovery_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_actions')
    op.drop_table('recovery_plans')
    op.drop_table('cascade_steps')
    op.drop_table('risk_snapshots')
    op.drop_table('disruptions')
    op.drop_table('dependency_edges')
    op.drop_table('bookings')
    op.drop_table('notifications')
    op.drop_table('itinerary_nodes')
    op.drop_table('activity_events')
    op.drop_table('trips')
    op.drop_table('travelers')
    # ### end Alembic commands ###

    # NOT auto-generated - added by hand. On Postgres, sa.Enum columns create
    # a separate named TYPE (CREATE TYPE ... AS ENUM) that DROP TABLE does
    # NOT remove. Left alone, a downgrade-then-upgrade cycle fails on the
    # second upgrade with "type already exists" (verified against a real
    # Postgres 16 instance). SQLite has no such type, so this only runs
    # against Postgres - `sa.Enum(...).drop()` on SQLite would be an error,
    # not a no-op, hence the dialect guard rather than just calling it
    # unconditionally with checkfirst=True.
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in (
            "activitytype", "changetype", "dependencytype", "disruptiontype",
            "edgestatus", "impactlevel", "nodecategory", "nodestatus",
            "notificationcategory", "notificationseverity", "risklevel",
            "snapshottype", "tripstatus",
        ):
            sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
