"""add email_notifications_opt_in to traveler

Revision ID: 3a54c862ee52
Revises: 7e91a2c4b5d6
Create Date: 2026-09-27 00:24:08.115633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a54c862ee52'
down_revision: Union[str, None] = '7e91a2c4b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Indexes are declared on the models but were never created by an earlier
    # migration. if_not_exists keeps this safe on databases that already have
    # them (e.g. local SQLite files built by create_all).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_events_timestamp'), 'activity_events', ['timestamp'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_activity_events_trip_id'), 'activity_events', ['trip_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_bookings_node_id'), 'bookings', ['node_id'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_bookings_trip_id'), 'bookings', ['trip_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_dependency_edges_source_id'), 'dependency_edges', ['source_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_dependency_edges_target_id'), 'dependency_edges', ['target_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_dependency_edges_trip_id'), 'dependency_edges', ['trip_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_itinerary_nodes_scheduled_start'), 'itinerary_nodes', ['scheduled_start'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_itinerary_nodes_trip_id'), 'itinerary_nodes', ['trip_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_notifications_trip_id'), 'notifications', ['trip_id'], unique=False, if_not_exists=True)
    op.add_column('travelers', sa.Column('email_notifications_opt_in', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.create_index(op.f('ix_trips_traveler_id'), 'trips', ['traveler_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_traveler_id'), table_name='trips', if_exists=True)
    op.drop_column('travelers', 'email_notifications_opt_in')
    op.drop_index(op.f('ix_notifications_trip_id'), table_name='notifications', if_exists=True)
    op.drop_index(op.f('ix_itinerary_nodes_trip_id'), table_name='itinerary_nodes', if_exists=True)
    op.drop_index(op.f('ix_itinerary_nodes_scheduled_start'), table_name='itinerary_nodes', if_exists=True)
    op.drop_index(op.f('ix_dependency_edges_trip_id'), table_name='dependency_edges', if_exists=True)
    op.drop_index(op.f('ix_dependency_edges_target_id'), table_name='dependency_edges', if_exists=True)
    op.drop_index(op.f('ix_dependency_edges_source_id'), table_name='dependency_edges', if_exists=True)
    op.drop_index(op.f('ix_bookings_trip_id'), table_name='bookings', if_exists=True)
    op.drop_index(op.f('ix_bookings_node_id'), table_name='bookings', if_exists=True)
    op.drop_index(op.f('ix_activity_events_trip_id'), table_name='activity_events', if_exists=True)
    op.drop_index(op.f('ix_activity_events_timestamp'), table_name='activity_events', if_exists=True)
    # ### end Alembic commands ###
