import { useEffect, useMemo, useState } from 'react';
import { useApp } from '@/store/AppContext';
import { DisruptionModal } from '@/components/disruption/DisruptionModal';
import { PageHeader } from '@/components/ui/PageHeader';
import { getWeather, type WeatherSnapshot } from '@/services/weather';
import { cn } from '@/lib/utils';
import { Plane, AlertTriangle, CheckCircle2, ArrowRight, ShieldCheck, Wallet, Zap } from 'lucide-react';
import { MetricCard } from '@/components/ui/MetricCard';

interface OverviewProps { onNavigate: (page: string) => void; }
export function Overview({ onNavigate }: OverviewProps) {
  const { trip, phase, activeDisruption, recoveryOptions, appliedRecovery } = useApp();
  const [disruptionOpen,setDisruptionOpen]=useState(false); const [weather,setWeather]=useState<WeatherSnapshot|null>(null);
  const atRisk = trip.nodes.filter(n=>n.status==='at-risk').length; const broken = trip.nodes.filter(n=>n.status==='broken').length;
  const weatherNode = useMemo(()=>trip.nodes.find(n=>n.lat!=null&&n.lng!=null)||null,[trip.nodes]);
  useEffect(()=>{ if(!weatherNode?.lat||!weatherNode?.lng)return; getWeather(weatherNode.lat,weatherNode.lng).then(setWeather).catch(()=>setWeather(null)); },[weatherNode?.id,weatherNode?.lat,weatherNode?.lng]);
  const needsAttention = atRisk>0 || broken>0 || phase==='disrupted' || phase==='analyzing' || phase==='recovering';
  const statusText = phase==='recovered'?'Your journey is back on track.':needsAttention?'Your journey needs attention.':'Your journey is on track.';
  const actionText = phase==='recovering'?'Review recovery options':phase==='disrupted'||phase==='analyzing'?'See what is affected':needsAttention?'Understand what needs attention':'Report a problem';
  const actionPage = phase==='recovering'?'recovery':phase==='disrupted'||phase==='analyzing'?'impact':'risk';
  return <div>
    <PageHeader title={`${trip.name || 'Your journey'}`} description={`${trip.startDate} — ${trip.endDate} · ${trip.route}`} crumbs={['Home']} onNavigate={onNavigate} />
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-gradient-to-r from-white to-safar-sky/5 px-5 py-4 shadow-card"><div><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Journey status</div><div className="mt-1 flex items-center gap-2 text-lg font-bold text-slate-900"><span className={cn('h-2.5 w-2.5 rounded-full',needsAttention?'bg-safar-risk':'bg-safar-safe')}/>{statusText}</div></div><button onClick={()=>setDisruptionOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-safar-blue px-4 py-2.5 text-sm font-semibold text-white shadow-card"><Zap className="h-4 w-4"/>Report a problem</button></div>

    {needsAttention && <button onClick={()=>onNavigate(actionPage)} className="mb-5 block w-full rounded-2xl border-2 border-safar-saffron/40 bg-white p-5 text-left shadow-card transition hover:-translate-y-0.5 hover:border-safar-saffron"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-safar-saffron/10 text-safar-saffron"><AlertTriangle className="h-6 w-6"/></div><div className="flex-1"><div className="text-[10px] font-bold uppercase tracking-wider text-safar-saffron">Needs your attention</div><h2 className="mt-1 text-lg font-bold text-slate-900">{activeDisruption?.label || `${atRisk} booking${atRisk===1?'':'s'} need${atRisk===1?'s':''} attention`}</h2><p className="mt-1 max-w-2xl text-sm text-slate-600">{activeDisruption?'SafarSathi has traced the disruption through your itinerary. See what breaks and why.':'One or more journey dependencies have moved below a safe threshold.'}</p></div><span className="inline-flex items-center gap-2 text-sm font-semibold text-safar-blue">{actionText}<ArrowRight className="h-4 w-4"/></span></div></button>}

    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold text-slate-500">Journey Health</div><div className="mt-1 text-4xl font-bold text-slate-900">{trip.healthScore}<span className="text-base font-medium text-slate-400"> / 100</span></div></div><div className="flex h-16 w-16 items-center justify-center rounded-full border-8 border-slate-100"><div className="text-xs font-bold text-safar-blue">{trip.healthScore}</div></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-safar-blue transition-all duration-700" style={{width:`${trip.healthScore}%`}}/></div><div className="mt-4 grid grid-cols-3 gap-3 text-center"><MiniStat value={trip.nodes.length} label="Bookings"/><MiniStat value={atRisk} label="At risk" warn={atRisk>0}/><MiniStat value={broken} label="Broken" danger={broken>0}/></div></section>
      <section className="rounded-2xl border border-safar-ai/20 bg-safar-ai/5 p-5 shadow-card"><div className="flex items-center gap-2"><span className="text-safar-ai">✦</span><span className="text-[10px] font-bold uppercase tracking-wider text-safar-ai">SAFARSATHI INSIGHT</span></div><h2 className="mt-3 text-lg font-bold text-slate-900">Live conditions at your next location</h2>{weather?<div className="mt-4 grid grid-cols-3 gap-3"><WeatherStat value={`${weather.temperature}°C`} label="Temperature"/><WeatherStat value={`${weather.precipitationProbability}%`} label="Rain chance"/><WeatherStat value={weather.label} label="Conditions"/></div>:<p className="mt-3 text-sm text-slate-600">Live weather is temporarily unavailable. Your existing risk assessment remains available.</p>}<button onClick={()=>onNavigate('risk')} className="mt-4 text-xs font-semibold text-safar-ai">View risk details →</button></section>
    </div>

    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">Your Journey</h2><p className="mt-1 text-xs text-slate-500">A quick view of the itinerary and current status.</p></div><button onClick={()=>onNavigate('journey')} className="text-xs font-semibold text-safar-blue">View full journey →</button></div><div className="mt-5 flex gap-3 overflow-x-auto pb-1">{trip.nodes.map((node,i)=><div key={node.id} className="flex min-w-[190px] items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className={cn('flex h-9 w-9 shrink-0 items-center justify-center rounded-full',node.status==='at-risk'?'bg-safar-saffron/10 text-safar-saffron':node.status==='broken'?'bg-safar-broken/10 text-safar-broken':'bg-safar-safe/10 text-safar-safe')}>{node.category==='flight'?<Plane className="h-4 w-4"/>:<CheckCircle2 className="h-4 w-4"/>}</div><div className="min-w-0"><div className="truncate text-xs font-semibold text-slate-900">{node.title}</div><div className="truncate text-[10px] text-slate-500">{node.scheduledTime}</div></div></div>)}</div></section>

    <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><MetricCard icon={<Plane className="h-4 w-4"/>} label="Bookings" value={trip.nodes.length} animate={false}/><MetricCard icon={<AlertTriangle className="h-4 w-4"/>} label="At risk" value={atRisk} accent="amber" animate={false}/><MetricCard icon={<ShieldCheck className="h-4 w-4"/>} label="Value protected" value={trip.tripValue} prefix="₹" animate={true}/><MetricCard icon={<Wallet className="h-4 w-4"/>} label="Broken" value={broken} accent="red" animate={false}/></section>

    {appliedRecovery && <div className="mt-5 rounded-2xl border border-safar-safe/20 bg-safar-safe/5 p-4"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-safar-safe"/><div><div className="text-sm font-semibold text-slate-900">Recovery applied successfully</div><div className="text-xs text-slate-600">{appliedRecovery.bookingsPreserved}/{appliedRecovery.totalBookings} commitments preserved.</div></div></div></div>}
    <DisruptionModal open={disruptionOpen} onClose={()=>setDisruptionOpen(false)} />
  </div>;
}
function MiniStat({value,label,warn,danger}:{value:number;label:string;warn?:boolean;danger?:boolean}){return <div><div className={cn('text-lg font-bold',danger?'text-safar-broken':warn?'text-safar-saffron':'text-slate-900')}>{value}</div><div className="text-[10px] text-slate-500">{label}</div></div>}
function MiniCard({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-card"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-safar-blue/10 text-safar-blue">{icon}</div><div className="mt-3 text-lg font-bold text-slate-900">{value}</div><div className="text-[11px] text-slate-500">{label}</div></div>}
function WeatherStat({value,label}:{value:string;label:string}){return <div className="rounded-xl bg-white/70 p-3"><div className="text-sm font-bold text-slate-900">{value}</div><div className="mt-1 text-[10px] text-slate-500">{label}</div></div>}
