import { useEffect, useState } from 'react';
import { useApp } from '@/store/AppContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { ScoreBar } from '@/components/ui/ScoreBar';
import { ScoreRing } from '@/components/ui/ScoreRing';
import { RiskBadge } from '@/components/ui/RiskBadge';
import * as api from '@/services/api';
import { getWeather, type WeatherSnapshot } from '@/services/weather';
import { useLocalStorageState } from '@/lib/useLocalStorageState';
import type { RiskCardData } from '@/types';
import { cn } from '@/lib/utils';
import { AlertTriangle, CloudRain, CheckCircle2, Clock, Building2, Link2, ArrowRight } from 'lucide-react';

export function RiskIntelligence({ onNavigate }: { onNavigate?: (page:string)=>void }) {
  const { tripId, trip } = useApp();
  const [risk,setRisk]=useState<api.RiskAnalysis|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [weather,setWeather]=useState<WeatherSnapshot|null>(null); const [step,setStep]=useState(0);
  const [thresholds]=useLocalStorageState('safarsathi.settings.riskThresholds',{connection:60,schedule:50});
  const load=()=>{if(!tripId){setRisk(null);setLoading(false);return;}let cancelled=false;setLoading(true);setError(null);setStep(0);api.getRiskAnalysis(tripId).then(d=>{if(!cancelled)setRisk(d)}).catch(e=>{if(!cancelled){setRisk(null);setError(e instanceof api.ApiError?e.message:'Could not load risk analysis.')}}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}};
  useEffect(load,[tripId,trip.healthScore]);
  useEffect(()=>{if(!loading){setStep(4);return} const timers=[1,2,3].map((n,i)=>window.setTimeout(()=>setStep(n),(i+1)*500));return()=>timers.forEach(clearTimeout)},[loading]);
  const weatherNode=trip.nodes.find(n=>n.lat!=null&&n.lng!=null);
  useEffect(()=>{if(!weatherNode?.lat||!weatherNode?.lng)return;getWeather(weatherNode.lat,weatherNode.lng).then(setWeather).catch(()=>setWeather(null))},[weatherNode?.id,weatherNode?.lat,weatherNode?.lng]);
  const shown=risk?.cards.filter(c=>c.riskPercent >= (c.riskType.toLowerCase().includes('connection')?thresholds.connection:thresholds.schedule)) ?? [];
  return <div><PageHeader title="Risk Intelligence" description="Proactive signals that help you act before a disruption becomes a problem." crumbs={['Home','Risks']} onNavigate={onNavigate}/>
    {error?<div className="rounded-2xl border border-safar-broken/20 bg-white p-8 text-center shadow-card"><AlertTriangle className="mx-auto h-7 w-7 text-safar-broken"/><h2 className="mt-3 font-semibold text-slate-900">We couldn’t load the latest risk picture</h2><p className="mt-1 text-sm text-slate-600">{error}</p><button onClick={load} className="mt-4 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Retry</button></div>:
    loading?<LoadingRisk step={step}/>:risk&&<>
      <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><ScoreRing score={risk.score.tripResilience} size={150} label="Resilience"/><div className="mt-3 text-center"><div className="text-sm font-bold text-slate-900">Journey resilience</div><p className="mt-1 text-xs text-slate-500">A single view of your current vulnerability.</p></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-slate-900">Risk breakdown</h2><span className="text-[10px] text-slate-500">Live itinerary analysis</span></div><div className="mt-5 space-y-4"><ScoreBar label="Connection risk" value={risk.score.connectionRisk} color="red"/><ScoreBar label="Schedule risk" value={risk.score.scheduleRisk} color="amber"/><ScoreBar label="Weather risk" value={risk.score.weatherRisk} color="cyan"/><ScoreBar label="Vendor risk" value={risk.score.vendorRisk} color="emerald"/></div></section></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">At-risk bookings</h2><p className="mt-1 text-xs text-slate-500">Only items above your alert threshold.</p></div><span className="rounded-full bg-safar-saffron/10 px-2.5 py-1 text-[10px] font-bold text-safar-saffron">{shown.length} need attention</span></div>{shown.length===0?<EmptyRisk/>:<div className="mt-4 space-y-3">{shown.map((card,i)=><RiskCard key={card.nodeId} card={card} delay={i*80} onNavigate={onNavigate}/>)}</div>}</section><section className="rounded-2xl border border-safar-ai/20 bg-safar-ai/5 p-5 shadow-card"><div className="flex items-center gap-2"><span className="text-safar-ai">✦</span><span className="text-[10px] font-bold uppercase tracking-wider text-safar-ai">SAFARSATHI INSIGHT</span></div><h2 className="mt-3 text-lg font-bold text-slate-900">Live weather signal</h2>{weather?<><div className="mt-4 flex items-end gap-4"><CloudRain className="h-10 w-10 text-safar-blue"/><div><div className="text-3xl font-bold text-slate-900">{weather.temperature}°C</div><div className="text-xs text-slate-600">{weather.label}</div></div></div><div className="mt-4 grid grid-cols-2 gap-3"><WeatherMetric value={`${weather.precipitationProbability}%`} label="Precipitation chance"/><WeatherMetric value={`${weather.windSpeed} km/h`} label="Wind speed"/></div></>:<p className="mt-3 text-sm text-slate-600">Live weather is temporarily unavailable; risk scoring remains visible.</p>}</section></div>
      <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">What could go wrong?</h2><p className="mt-1 text-xs text-slate-500">Understand the reason before deciding what to do.</p></div></div>{risk.cards.length===0?<EmptyRisk/>:<div className="mt-4 grid gap-3 sm:grid-cols-2">{[...risk.cards].sort((a,b)=>b.riskPercent-a.riskPercent).slice(0,4).map(c=><div key={c.nodeId} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2"><ScenarioIcon type={c.riskType}/><span className="text-xs font-semibold text-slate-900">{c.nodeLabel}</span></div><p className="mt-2 text-xs leading-5 text-slate-600">{c.recommendation}</p><button onClick={()=>onNavigate?.('impact')} className="mt-3 inline-flex items-center gap-1 text-[11px] font-semibold text-safar-blue">See impact <ArrowRight className="h-3 w-3"/></button></div>)}</div>}</section>
    </>}
  </div>;
}
function LoadingRisk({step}:{step:number}){const items=['Checking connections','Checking downstream bookings','Calculating exposure','Preparing recovery options'];return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><h2 className="text-sm font-bold text-slate-900">Building your risk picture</h2><div className="mt-5 space-y-4">{items.map((x,i)=><div key={x} className="flex items-center gap-3"><span className={cn('flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold',step>i?'bg-safar-safe/10 text-safar-safe':step===i?'bg-safar-blue/10 text-safar-blue':'bg-slate-100 text-slate-400')}>{step>i?'✓':step===i?'●':'○'}</span><span className={cn('text-sm',step===i?'font-semibold text-slate-900':'text-slate-600')}>{x}</span></div>)}</div></div>}
function RiskCard({card,delay,onNavigate}:{card:RiskCardData;delay:number;onNavigate?: (p:string)=>void}){return <div className="rounded-xl border border-slate-200 bg-white p-4 animate-fade-in-up" style={{animationDelay:`${delay}ms`}}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold text-slate-900">{card.nodeLabel}</div><div className="mt-1 text-[10px] text-slate-500">{card.riskType}</div></div><RiskBadge level={card.riskLevel} percent={card.riskPercent}/></div><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-slate-600"><span>Impact: {card.downstreamImpact} booking(s)</span>{card.buffer&&<span>· Buffer {card.buffer}</span>}</div><div className="mt-3 rounded-lg bg-safar-saffron/5 p-3 text-xs text-slate-700"><b>Recommended:</b> {card.recommendation}</div><button onClick={()=>onNavigate?.('impact')} className="mt-3 text-xs font-semibold text-safar-blue">Understand impact →</button></div>}
function ScenarioIcon({type}:{type:string}){const t=type.toLowerCase();const Icon=t.includes('weather')?CloudRain:t.includes('hotel')||t.includes('vendor')?Building2:t.includes('connection')?Link2:Clock;return <Icon className="h-4 w-4 text-safar-blue"/>}
function EmptyRisk(){return <div className="mt-5 rounded-2xl border border-dashed border-safar-safe/30 bg-safar-safe/5 p-8 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-safar-safe"/><h3 className="mt-3 text-sm font-bold text-slate-900">Everything looks good</h3><p className="mt-1 text-xs text-slate-600">No booking currently crosses your alert threshold.</p></div>}
function WeatherMetric({value,label}:{value:string;label:string}){return <div className="rounded-xl bg-white/70 p-3"><div className="text-sm font-bold text-slate-900">{value}</div><div className="mt-1 text-[10px] text-slate-500">{label}</div></div>}
