import { useMemo, useState } from 'react';
import { useApp } from '@/store/AppContext';
import { useToast } from '@/components/ui/ToastProvider';
import { PageHeader } from '@/components/ui/PageHeader';
import { ScoreBar } from '@/components/ui/ScoreBar';
import { cn } from '@/lib/utils';
import { formatCurrency, formatDuration } from '@/lib/status';
import type { RecoveryOption } from '@/types';
import { BeforeAfterView } from '@/components/recovery/BeforeAfterView';
import { Check, Sparkles, Wallet, Clock, Shield, TrendingUp, RotateCcw, GitCompare, AlertCircle, LifeBuoy, ShieldCheck } from 'lucide-react';

export function RecoveryCenter({ onNavigate }: { onNavigate?: (page: string) => void }) {
  const { recoveryOptions, selectedRecovery, selectRecovery, applyRecoveryPlan, activeDisruption, phase, appliedRecovery } = useApp();
  const { addToast } = useToast();
  const [confirm, setConfirm] = useState<RecoveryOption | null>(null);
  const [compareOpen, setCompareOpen] = useState(false);
  const sorted = useMemo(()=>recoveryOptions.filter(o=>o.feasible !== false).sort((a,b)=>b.score-a.score),[recoveryOptions]);
  const unavailable = useMemo(()=>recoveryOptions.find(o=>o.feasible === false),[recoveryOptions]);

  const apply = async () => { if(!confirm) return; try { await applyRecoveryPlan(confirm.id); addToast('success','Recovery applied',`${confirm.bookingsPreserved}/${confirm.totalBookings} commitments preserved.`); setConfirm(null); } catch { addToast('error','Could not apply recovery','Please try again.'); } };
  if (phase === 'idle') return <EmptyState icon={<LifeBuoy/>} title="No active disruption" text="Recovery plans appear here only when SafarSathi finds a journey problem."/>;
  if (recoveryOptions.length === 0 && phase !== 'recovered') return <div><PageHeader title="Recovery Center" description="SafarSathi is finding feasible ways forward." crumbs={['Home','Journey','Recovery']} onNavigate={onNavigate}/><LoadingOptions /></div>;
  if (phase === 'recovered' && appliedRecovery) return <Recovered recovery={appliedRecovery} onNavigate={onNavigate}/>;

  return <div><PageHeader title="Recovery Center" description="Choose a feasible way forward based on your priorities." crumbs={['Home','Risks','Recovery']} onNavigate={onNavigate}/>
    {activeDisruption && <div className="mb-5 rounded-2xl border border-safar-broken/20 bg-safar-broken/5 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-safar-broken">Current disruption</div><div className="mt-1 text-sm font-semibold text-slate-900">{activeDisruption.label}</div><div className="mt-1 text-xs text-slate-600">{activeDisruption.downstreamImpact} downstream booking(s) affected.</div></div>}
    {unavailable && <div className="mb-5 rounded-2xl border border-safar-broken/20 bg-safar-broken/5 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-safar-broken">Provider unavailable</div><div className="mt-1 text-sm font-semibold text-slate-900">No recovery options from this provider</div><p className="mt-1 text-xs leading-5 text-slate-600">{unavailable.providerReason || unavailable.description}</p></div>}
    {sorted.length > 0 && <><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">{sorted.length} recovery plans</h2><p className="text-xs text-slate-500">Select a plan to see how its score is built.</p></div><button onClick={()=>setCompareOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-700"><GitCompare className="h-3.5 w-3.5"/> {compareOpen?'Hide comparison':'Compare plans'}</button></div>
    {compareOpen && <Comparison options={sorted} onSelect={(id)=>{selectRecovery(id);setCompareOpen(false)}}/>}
    <div className="space-y-3">{sorted.map((option,i)=><RecoveryOptionCard key={option.id} option={option} rank={i} selected={selectedRecovery===option.id} onSelect={()=>selectRecovery(option.id)} onApply={()=>setConfirm(option)}/>)}</div></>}
    {confirm && <ConfirmRecovery option={confirm} onCancel={()=>setConfirm(null)} onConfirm={apply}/>} 
  </div>;
}

function RecoveryOptionCard({option,rank,selected,onSelect,onApply}:{option:RecoveryOption;rank:number;selected:boolean;onSelect:()=>void;onApply:()=>void}) { return <div className={cn('relative rounded-2xl border bg-white p-5 shadow-card transition-all animate-fade-in-up',selected?'border-safar-blue/50 ring-2 ring-safar-blue/10':'border-slate-200 hover:border-safar-blue/20')} style={{animationDelay:`${rank*90}ms`}}>
  {rank===0&&<div className="absolute -top-2 left-4 flex items-center gap-1 rounded-full bg-safar-blue px-2.5 py-1 text-[10px] font-bold text-white"><Sparkles className="h-3 w-3"/> RECOMMENDED</div>}
  <button onClick={onSelect} className="w-full text-left"><div className="flex items-start justify-between gap-4"><div><span className={cn('rounded-full border px-2 py-1 text-[10px] font-bold', option.tagColor==='amber'?'border-safar-saffron/30 bg-safar-saffron/10 text-safar-saffron':option.tagColor==='green'?'border-safar-safe/30 bg-safar-safe/10 text-safar-safe':option.tagColor==='violet'?'border-safar-ai/20 bg-safar-ai/5 text-safar-ai':'border-safar-blue/20 bg-safar-blue/10 text-safar-blue')}>{option.tag}</span><h3 className="mt-3 text-base font-bold text-slate-900">{option.name}</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-600">{option.description}</p></div><div className="text-right"><div className="text-2xl font-bold text-slate-900">{option.score}</div><div className="text-[10px] text-slate-500">/100</div></div></div></button>
  <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric icon={<Wallet/>} label="Cost" value={option.costDelta>0?`+${formatCurrency(option.costDelta)}`:formatCurrency(Math.abs(option.costDelta))}/><Metric icon={<Clock/>} label="Time" value={formatDuration(option.timeImpactMinutes)}/><Metric icon={<Shield/>} label="Preserved" value={`${option.bookingsPreserved}/${option.totalBookings}`} green/><Metric icon={<TrendingUp/>} label="Risk" value={option.residualRisk} risk={option.residualRisk}/></div>
  {selected&&<div className="mt-4 border-t border-slate-200 pt-4 animate-fade-in"><div className="mb-3 text-xs font-semibold text-slate-900">Score breakdown</div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><ScoreBar label="Cost efficiency" value={option.scoreBreakdown.cost} color="emerald"/><ScoreBar label="Speed" value={option.scoreBreakdown.speed} color="blue"/><ScoreBar label="Preservation" value={option.scoreBreakdown.preservation} color="blue"/><ScoreBar label="Comfort" value={option.scoreBreakdown.comfort} color="amber"/></div></div>}
  <div className="mt-4 flex flex-wrap gap-2"><button onClick={onApply} className="inline-flex items-center gap-2 rounded-xl bg-safar-blue px-3.5 py-2 text-xs font-semibold text-white"><Check className="h-3.5 w-3.5"/>Review & apply</button><button onClick={onSelect} className="rounded-xl border border-slate-300 px-3.5 py-2 text-xs font-semibold text-slate-700">{selected?'Hide breakdown':'Why this plan?'}</button></div>
</div>; }
function Metric({icon,label,value,green,risk}:{icon:React.ReactNode;label:string;value:string;green?:boolean;risk?:string}){return <div className="rounded-xl border border-slate-200 bg-slate-50 p-2.5"><div className="flex items-center gap-1 text-slate-500">{icon}<span className="text-[10px]">{label}</span></div><div className={cn('mt-1 text-sm font-bold',green?'text-safar-safe':risk==='low'?'text-safar-safe':risk==='medium'?'text-safar-risk':risk==='high'?'text-safar-broken':'text-slate-900')}>{value}</div></div>}
function Comparison({options,onSelect}:{options:RecoveryOption[];onSelect:(id:string)=>void}){return <div className="mb-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-3 shadow-card"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-slate-200 text-[10px] uppercase text-slate-500"><th className="p-2">Plan</th><th className="p-2">Cost</th><th className="p-2">Time</th><th className="p-2">Preserved</th><th className="p-2">Risk</th><th className="p-2">Score</th></tr></thead><tbody>{options.map(o=><tr key={o.id} onClick={()=>onSelect(o.id)} className="cursor-pointer border-b border-slate-100 text-xs hover:bg-slate-50"><td className="p-3 font-semibold text-slate-900">{o.name}</td><td className="p-3">+{formatCurrency(o.costDelta)}</td><td className="p-3">{formatDuration(o.timeImpactMinutes)}</td><td className="p-3 text-safar-safe">{o.bookingsPreserved}/{o.totalBookings}</td><td className="p-3">{o.residualRisk}</td><td className="p-3 font-bold text-safar-blue">{o.score}</td></tr>)}</tbody></table></div>}
function ConfirmRecovery({option,onCancel,onConfirm}:{option:RecoveryOption;onCancel:()=>void;onConfirm:()=>void}){return <div className="fixed inset-0 z-[160] flex items-center justify-center bg-safar-navy/15 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-safar-blue/10 text-safar-blue"><ShieldCheck/></div><div><h2 className="font-bold text-slate-900">Confirm recovery</h2><p className="text-xs text-slate-500">Nothing changes until you approve it.</p></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="font-semibold text-slate-900">{option.name}</div><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div>Additional cost<b className="block mt-1 text-slate-900">₹{option.costDelta.toLocaleString('en-IN')}</b></div><div>Time impact<b className="block mt-1 text-slate-900">{formatDuration(option.timeImpactMinutes)}</b></div><div>Preserved<b className="block mt-1 text-safar-safe">{option.bookingsPreserved}/{option.totalBookings}</b></div><div>Residual risk<b className="block mt-1 text-slate-900">{option.residualRisk}</b></div></div></div><div className="mt-5 flex gap-2"><button onClick={onCancel} className="flex-1 rounded-xl border border-slate-300 py-2.5 text-sm font-semibold text-slate-700">Cancel</button><button onClick={onConfirm} className="flex-1 rounded-xl bg-safar-blue py-2.5 text-sm font-semibold text-white">Confirm & Apply</button></div></div></div>}
function LoadingOptions(){return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><div className="text-sm font-bold text-slate-900">Finding feasible recovery options</div><div className="mt-5 space-y-4 text-xs"><Step text="Checking available alternatives" done/><Step text="Validating itinerary dependencies" done/><Step text="Scoring cost, speed and preservation" active/><Step text="Preparing recovery options"/></div></div>}
function Step({text,done,active}:{text:string;done?:boolean;active?:boolean}){return <div className="flex items-center gap-3"><span className={cn('flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-bold',done?'bg-safar-safe/10 text-safar-safe':active?'bg-safar-blue/10 text-safar-blue':'bg-slate-100 text-slate-400')}>{done?'✓':active?'●':'○'}</span><span className={cn(active?'text-slate-900 font-semibold':'text-slate-600')}>{text}</span></div>}
function EmptyState({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex min-h-[420px] items-center justify-center"><div className="max-w-md text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-500">{icon}</div><h2 className="mt-4 text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-600">{text}</p></div></div>}
function Recovered({recovery,onNavigate}:{recovery:RecoveryOption;onNavigate?: (p:string)=>void}){return <div><PageHeader title="Journey recovered" description="Your itinerary has been recalculated and stabilized." crumbs={['Home','Journey','Recovery']} onNavigate={onNavigate}/><div className="rounded-2xl border border-safar-safe/20 bg-white p-6 shadow-card"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-safar-safe/10 text-safar-safe"><Check/></div><div><h2 className="font-bold text-slate-900">Your journey is back on track</h2><p className="text-xs text-slate-600">{recovery.name}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric icon={<Shield/>} label="Preserved" value={`${recovery.bookingsPreserved}/${recovery.totalBookings}`} green/><Metric icon={<Wallet/>} label="Additional cost" value={`+${formatCurrency(recovery.costDelta)}`}/><Metric icon={<Clock/>} label="Time impact" value={formatDuration(recovery.timeImpactMinutes)}/><Metric icon={<ShieldCheck/>} label="Residual risk" value={recovery.residualRisk} green/></div><button onClick={()=>onNavigate?.('overview')} className="mt-5 rounded-xl bg-safar-blue px-4 py-2.5 text-sm font-semibold text-white">Back to Home</button></div><div className="mt-5"><BeforeAfterView/></div></div>}
